### ISSUE TITLE
HMAC Authentication error

### ISSUE THREAD

**Issue by Flat** [flamusdiu/python-pia#22]
All connection configs for openvpn using pia -a error with 

```
Authenticate/Decrypt packet error: packet HMAC authentication failed
```

**Comment by flamusdiu** [comment]
umm, that's a first for that error. So, none of the configs work from cli using OpenVPN?

**Comment by Flat** [comment]
Correct. downloading the configs directly and placing them in /etc/OpenVPN/ works fine though.

**Comment by flamusdiu** [comment]
@Flat, sigh, okay. Let me take a look at the PIA configs. I wonder if they changed them.

**Comment by Flat** [comment]
@flamusdiu looking through their table and comparing config files generated by python-pia and the ones taken from their website they seem to have changed the hashing and encryption scheme for port 1198. port 1198 is now `AES-128-CBC` and `SHA1` while 1197 is `AES-256-CBC` and `SHA256` using the 4096 certificates. it also looks like python-pia is ignoring `/etc/private-internet-access/pia.conf` and using 1198 for the port when 1197 is set in the config.

**Comment by flamusdiu** [comment]
I thought that's the way I set it. Either way, I may just drop configuring it that way. There are a limited number of options based on #17 findings. I'll just reconfigure it to use those options and just allow ppl to select which one they want. I am also thinking of DLing the certs directly from PIA (there are 3 of them) instead of pulling them from the Zips.

**Comment by flamusdiu** [comment]
Pushed update to dev branch. Going to close this one in favor of #17 .
